# Generated by Django 4.0.4 on 2022-06-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.BinaryField(blank=True),
        ),
    ]
