# Generated by Django 4.0.4 on 2022-08-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_token_alter_timelog_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.BinaryField(blank=True, null=True, unique=True, verbose_name='API Token'),
        ),
    ]
